name: build and deploy

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Create publish folder
        run: mkdir public

      - name: Copy index.html to publish folder
        run: cp index.html public

      - name: Copy logo to publish folder
        run: cp logo.png public

      - name: Copy README to publish folder
        run: cp README.md public

      - name: Copy source to publish folder
        run: cp -r Coolapk-API public

      - name: Change index.html base-tag
        run: sed -i 's/<base href="\/" \/>/<base href="\/Coolapk-API-Collect\/" \/>/g' public/index.html

      - name: Change README link
        run: sed -i 's/Coolapk-API\///g' public/README.md

      - name: Add .nojekyll file
        run: touch public/.nojekyll

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: public

  deploy:
    needs: build

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
